# Generated by Django 5.0.3 on 2024-05-05 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_category_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subscribers',
        ),
    ]
